# Generated by Django 5.2.1 on 2025-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='outlet_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
