# Generated by Django 5.2.1 on 2025-05-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_lead_created_at_alter_lead_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='outlet_type',
            new_name='outlet',
        ),
    ]
